sudo: false

language: python

python:
  - "2.7"

install:
  - pip install codecov
  - codecov --token=697f5051-f61d-4148-bea5-c4f9c411cf9e

script:
  - python -m pytest --capture=no

after_success:
  - codecov
