version: '2'

services:
    web:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./blazemeter:/blazemeter
            - ./site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
    php:
        build: php/
        volumes:
            - ./blazemeter:/blazemeter
        networks:
            - code-network
    mongo:
      image: mongo:3.4.9
      command: --dbpath=/data/db --port 27017
      ports:
        - 27017:27017
      networks:
        - code-network
    redis:
          image: redis:latest
          ports:
            - 6379:6379
          networks:
            - code-network

networks:
    code-network:
        driver: bridge
